USDT:
  # address of NATIVE (Ethereum ERC20 USDT Gateway)
  native:
    - 167.99.6.79 # host
    - 8089   # port

  # address of TARGET (BitShares FINTEH.USDT Gateway)
  target:
    - 167.99.6.79 # host
    - 8889   # port


#Add more remote gateways servers addresses here like:

#BTC:
#  native:
#    host: some.btc_host
#    port: 55551
#  target:
#    host: some.finteh.btc_host
#    port: 12345
# etc