---

- name: Install bitshares gateway
  hosts: bitshares_gateway_hosts
  gather_facts: false

  tasks:
  - name: Creates bitshares gateway directory
    file:
      path: /var/www/gateway.commodity.llc/g_html/bitshares_gateway/
      state: directory
      recurse: yes

  - name: Clone bitshares gateway repo
    git:
      repo: https://github.com/technozhantomz/bitshares_gateway.git
      dest: /var/www/gateway.commodity.llc/g_html/bitshares_gateway/
      accept_hostkey: yes
      force: yes
      version: master
      track_submodules: yes

  - name: Copy docker-compose.yml for bitshares_gateway folder
    copy:
      src: bitshares_gateway/docker-compose.yml
      dest: /var/www/gateway.commodity.llc/g_html/bitshares_gateway/

  - name: Copy .env for bitshares gateway
    copy:
      src: bitshares_gateway/.env
      dest: /var/www/gateway.commodity.llc/g_html/bitshares_gateway/
      
  - name: Copy gateway.yml for booker_api folder
    copy:
      src: booker/gateway.yml
      dest: /opt/bitshares_gateway/

