---

- name: Install bitshares gateway
  hosts: bitshares_gateway_hosts
  gather_facts: false

  tasks:
  - name: Creates bitshares gateway directory
    file:
      path: /var/www/gateway.commodity.llc/g_html/bitshares_gateway/
      state: directory
      recurse: yes

  - name: Clone bitshares gateway repo
    git:
      repo: https://github.com/technozhantomz/bitshares_gateway.git
      dest: /var/www/gateway.commodity.llc/g_html/bitshares_gateway/
      accept_hostkey: yes
      force: yes
      version: master
      track_submodules: yes

  - name: Copy .env for bitshares gateway
    copy:
      src: bitshares_gateway/.env
      dest: /var/www/gateway.commodity.llc/g_html/bitshares_gateway/

  - name: Copy docker-compose.yml for bitshares_gateway folder
    copy:
      src: bitshares_gateway/docker-compose.yml
      dest: /var/www/gateway.commodity.llc/g_html/bitshares_gateway/

  - name: Copy gateway.yml for bitshares_gateway folder
    copy:
      src: bitshares_gateway/gateway.yml
      dest: /var/www/gateway.commodity.llc/g_html/bitshares_gateway/

  - name: Run docker containers
    shell: "cd /opt/bitshares_gateway/ && docker-compose up -d --no-deps gateway"
    environment:
      DATABASE_DRIVER: "postgres+psycopg2"
      DATABASE_PORT: 5433
      DATABASE_HOST: "167.99.6.79"
      DATABASE_USERNAME: "bitshares-gateway"
      DATABASE_PASSWORD: "bitshares-gateway"
      DATABASE_NAME: "bitshares-gateway"
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: 8889
      WS_HOST: "0.0.0.0"
      WS_PORT: 7082
